"""Add users table for authentication

Revision ID: 82e96fc4f1d4
Revises: cdb7fee4e428
Create Date: 2025-10-14 11:48:50.216184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82e96fc4f1d4'
down_revision: Union[str, None] = 'cdb7fee4e428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_documents_extracted_data_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_search_vector_gin', table_name='documents', postgresql_using='gin')
    op.drop_column('documents', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_documents_search_vector_gin', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_extracted_data_gin', 'documents', ['extracted_data'], unique=False, postgresql_using='gin')
    op.alter_column('documents', 'extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
